import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { updateHac } from '../lib/hac-update.mjs';
async function fixture(t) {
 const dir=await mkdtemp(join(tmpdir(),'hac-self-test-')); t.after(()=>rm(dir,{recursive:true,force:true}));
 const root=join(dir,'installed'), home=join(dir,'home'), source=join(dir,'src/hac');
 for(const d of [root,home,join(source,'bin'),join(root,'manifest'),join(source,'manifest')]) await mkdir(d,{recursive:true});
 await writeFile(join(root,'manifest/hac.json'),JSON.stringify({version:'1.0.0'}));
 await writeFile(join(source,'manifest/hac.json'),JSON.stringify({version:'1.1.0'}));
 await writeFile(join(source,'bin/hac'),'#!/bin/sh\necho hacVersion=1.1.0\n',{mode:0o755});
 execFileSync('tar',['--format=ustar','-czf',join(dir,'release.tgz'),'-C',join(dir,'src'),'hac'],{env:{...process.env,COPYFILE_DISABLE:'1'}});
 const archive=await readFile(join(dir,'release.tgz')); const manifest={version:'1.1.0',url:'https://example.test/hac.tgz',sha256:createHash('sha256').update(archive).digest('hex')};
 const calls=[]; const opts={env:{HOME:home,HAC_RELEASE_URL:'https://example.test/latest.json'},fetchImpl:async url=>new Response(url.endsWith('.json')?JSON.stringify(manifest):archive),run:(file,args)=>{calls.push([file,args]);return {status:0,stdout:'hacVersion=1.1.0\n'};},log:()=>{}};
 return {root,home,manifest,opts,calls};
}
test('missing feed still invokes Pi and returns its status',async t=>{const f=await fixture(t);delete f.opts.env.HAC_RELEASE_URL;f.opts.run=(file,args)=>{assert.equal(file,join(f.root,'bin/hac'));assert.deepEqual(args,['pi','update']);return {status:7};};assert.equal(await updateHac(f.root,f.opts),7);});
test('bad digest keeps installed hac',async t=>{const f=await fixture(t);f.manifest.sha256='0'.repeat(64);await assert.rejects(updateHac(f.root,f.opts),/checksum/);assert.equal(JSON.parse(await readFile(join(f.root,'manifest/hac.json'))).version,'1.0.0');assert.equal(f.calls.length,0);});
test('valid archive probes version then updates Pi before publication',async t=>{const f=await fixture(t);assert.equal(await updateHac(f.root,f.opts),0);assert.deepEqual(f.calls.map(x=>x[1]),[['version'],['pi','update']]);assert.equal(JSON.parse(await readFile(join(f.root,'manifest/hac.json'))).version,'1.1.0');});
test('failed Pi leaves hac unchanged',async t=>{const f=await fixture(t);f.opts.run=(_file,args)=>({status:args[0]==='pi'?9:0,stdout:'hacVersion=1.1.0\n'});assert.equal(await updateHac(f.root,f.opts),9);assert.equal(JSON.parse(await readFile(join(f.root,'manifest/hac.json'))).version,'1.0.0');});
test('publication failure restores hac and both Pi pointers',async t=>{const f=await fixture(t);const runtime=join(f.home,'.config/hiworks-agent-cli/runtime');await mkdir(runtime,{recursive:true});await writeFile(join(runtime,'active.json'),'original');await writeFile(join(runtime,'active.json.previous'),'previous');f.opts.run=(_file,args)=>{if(args[0]==='pi'){execFileSync('sh',['-c','printf changed > "$1"','sh',join(runtime,'active.json')]);}return {status:0,stdout:'hacVersion=1.1.0\n'};};let count=0;const {rename}=await import('node:fs/promises');f.opts.rename=async(a,b)=>{if(++count===2)throw new Error('publication failed');await rename(a,b);};await assert.rejects(updateHac(f.root,f.opts),/publication failed/);assert.equal(JSON.parse(await readFile(join(f.root,'manifest/hac.json'))).version,'1.0.0');assert.equal(await readFile(join(runtime,'active.json'),'utf8'),'original');assert.equal(await readFile(join(runtime,'active.json.previous'),'utf8'),'previous');});
test('symlink archive rejected before executing candidate',async t=>{const f=await fixture(t);const {symlink}=await import('node:fs/promises');await symlink('/tmp',join(f.root,'escape'));const out=join(f.root,'bad.tgz');execFileSync('tar',['--format=ustar','-czf',out,'-C',f.root,'escape'],{env:{...process.env,COPYFILE_DISABLE:'1'}});const bytes=await readFile(out);f.manifest.sha256=createHash('sha256').update(bytes).digest('hex');f.opts.fetchImpl=async url=>new Response(url.endsWith('.json')?JSON.stringify(f.manifest):bytes);await assert.rejects(updateHac(f.root,f.opts),/archive/);assert.equal(f.calls.length,0);});
test('concurrent update lock rejects before invoking Pi',async t=>{const f=await fixture(t);await mkdir(join(f.home,'.config/hiworks-agent-cli/runtime/locks/hac-update'),{recursive:true});await assert.rejects(updateHac(f.root,f.opts),/another hac update/);assert.equal(f.calls.length,0);});
test('dead updater PID lock is reclaimed',async t=>{const f=await fixture(t);const lock=join(f.home,'.config/hiworks-agent-cli/runtime/locks/hac-update');await mkdir(lock,{recursive:true});await writeFile(join(lock,'pid'),'2147483647\n');await writeFile(join(lock,'timestamp'),`${Math.floor(Date.now()/1000)}\n`);delete f.opts.env.HAC_RELEASE_URL;assert.equal(await updateHac(f.root,f.opts),0);});
test('runtime transaction lock excludes standalone Pi through publication rollback',async t=>{const f=await fixture(t);const {readFileSync,existsSync}=await import('node:fs');const lock=join(f.home,'.config/hiworks-agent-cli/runtime/locks/runtime');f.opts.run=(_file,args,env)=>{if(args[0]==='pi'){assert.equal(env.HAC_RUNTIME_LOCK_HELD,'1');assert.equal(readFileSync(join(lock,'pid'),'utf8').trim(),String(process.pid));const base=new URL('../lib/',import.meta.url).pathname;execFileSync('sh',['-c','. "$1/hac-env.sh"; . "$1/hac-lock.sh"; hac_release_lock runtime && exit 1; exit 0','sh',base],{env});assert.ok(existsSync(lock));}return {status:0,stdout:'hacVersion=1.1.0\n'};};let n=0;const {rename}=await import('node:fs/promises');f.opts.rename=async(a,b)=>{assert.ok(existsSync(lock));if(++n===2)throw new Error('publication failed');await rename(a,b);};await assert.rejects(updateHac(f.root,f.opts),/publication failed/);assert.equal(existsSync(lock),false);});
test('active runtime lock blocks self-update transaction',async t=>{const f=await fixture(t);const lock=join(f.home,'.config/hiworks-agent-cli/runtime/locks/runtime');await mkdir(lock,{recursive:true});await writeFile(join(lock,'pid'),`${process.pid}\n`);await writeFile(join(lock,'timestamp'),'1\n');await assert.rejects(updateHac(f.root,f.opts),/runtime.*lock|lock.*runtime/);assert.equal(f.calls.filter(x=>x[1][0]==='pi').length,0);});
for(const signal of ['SIGINT','SIGTERM']) test(`${signal} clears updater lock and permits another update`,async t=>{const f=await fixture(t);const {spawn}=await import('node:child_process');const {once}=await import('node:events');const script=`import {updateHac} from ${JSON.stringify(new URL('../lib/hac-update.mjs',import.meta.url).href)}; await updateHac(${JSON.stringify(f.root)},{fetchImpl:async()=>{console.log('ready');await new Promise(()=>{setInterval(()=>{},1000)});}});`;const child=spawn(process.execPath,['--input-type=module','-e',script],{env:{...process.env,...f.opts.env},stdio:['ignore','pipe','pipe']});t.after(()=>child.kill('SIGKILL'));await once(child.stdout,'data');const stopped=once(child,'exit');child.kill(signal);const [code]=await stopped;assert.equal(code,signal==='SIGINT'?130:143);const {existsSync}=await import('node:fs');assert.equal(existsSync(join(f.home,'.config/hiworks-agent-cli/runtime/locks/hac-update')),false);delete f.opts.env.HAC_RELEASE_URL;assert.equal(await updateHac(f.root,f.opts),0);});

for(const signal of ['SIGINT','SIGTERM']) test(`${signal} between publication renames leaves a complete install`,async t=>{
 const f=await fixture(t);const {rename}=await import('node:fs/promises');let count=0;
 f.opts.rename=async(a,b)=>{await rename(a,b);if(++count===1)process.emit(signal);};
 assert.equal(await updateHac(f.root,f.opts),signal==='SIGINT'?130:143);
 assert.equal(JSON.parse(await readFile(join(f.root,'manifest/hac.json'))).version,'1.1.0');
});
